### ISSUE TITLE
Issues in develop branch

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/prestashop-ui-kit#101]
I found some issues while browsing the preview on the develop branch:

1. Low contrast link color in informational alert:

<img width="1230" alt="Screenshot 2020-08-03 at 17 07 59" src="https://user-images.githubusercontent.com/1009343/89197421-f719ab80-d5ab-11ea-8fb0-a24f27a5dcc4.png">

2. Blue link in green alert, again low contrast (and arguably ugly :P)

<img width="1234" alt="Screenshot 2020-08-03 at 17 08 44" src="https://user-images.githubusercontent.com/1009343/89197458-0698f480-d5ac-11ea-8387-2bde0c37def0.png">

3. Low contrast in description text & icon color

<img width="1252" alt="Screenshot 2020-08-03 at 17 09 42" src="https://user-images.githubusercontent.com/1009343/89197548-2c25fe00-d5ac-11ea-9757-d866d5098b5b.png">

4. The warning text is low contrast; the warning color background looks a little "muddy" to me, perhaps we should pick a more orangey yellow instead.

<img width="373" alt="Screenshot 2020-08-03 at 17 10 14" src="https://user-images.githubusercontent.com/1009343/89197682-64c5d780-d5ac-11ea-812b-a4f6536d0637.png">

5. The warning badge looks even more muddy

<img width="721" alt="Screenshot 2020-08-03 at 17 11 54" src="https://user-images.githubusercontent.com/1009343/89197742-7a3b0180-d5ac-11ea-968e-cb280d36edda.png">

6. The warning buttons suffer from the same color/contrast problems:

<img width="551" alt="Screenshot 2020-08-03 at 17 12 40" src="https://user-images.githubusercontent.com/1009343/89197852-a3f42880-d5ac-11ea-966d-acfc925c4464.png">

7. Again, low contrast:

<img width="830" alt="Screenshot 2020-08-03 at 17 13 51" src="https://user-images.githubusercontent.com/1009343/89197948-c1c18d80-d5ac-11ea-9f43-2e81a02d7209.png">

8. Rounded background in the selected pill looks weird:

<img width="409" alt="Screenshot 2020-08-03 at 17 14 52" src="https://user-images.githubusercontent.com/1009343/89198049-e584d380-d5ac-11ea-8b8b-2c94073c3b59.png">

**Comment by eternoendless** [comment]
I'm aware the warning color does not officially belong to the UI kit but we should find a better shade nonetheless.

**Comment by prestascott** [comment]
Hi @eternoendless, thank you for your feedback!

1. I decided to change this informational alert by adding a blue border (#25B9D7) to easily identify it. An I changed all the links to a dark grey color (#363A41) and put it in bold and underlined.
![image](https://user-images.githubusercontent.com/54888056/91044742-12f5f780-e616-11ea-87c1-2827059b3e18.png)

2. I agree, blue doesn’t fit every colored background so it becomes dark grey. 
![image](https://user-images.githubusercontent.com/54888056/91044764-19846f00-e616-11ea-8871-006e5c6a3e87.png)

3. Text is supposed to be darker (#363A41). I changed the icon color into #FAB000.
![image](https://user-images.githubusercontent.com/54888056/91044786-243f0400-e616-11ea-9218-c21513910c9d.png)

4. These aren’t the colors that are supposed to be used, here they are:  
- Success alert: green #53D572 
- Error/danger alert: blue #25B9D7 
- Warning alert: red #F44336
- Info alert: orangey yellow #FAB000  
![image](https://user-images.githubusercontent.com/54888056/91044989-6ff1ad80-e616-11ea-9334-a393755c0cd2.png)

This is my second proposition which looks like the sticky alerts:
![image](https://user-images.githubusercontent.com/54888056/91045086-96afe400-e616-11ea-8636-e1185b716cd3.png)

5. The warning badges won’t be "muddy" anymore with the orangey yellow #FAB000.
6. These buttons doesn’t exist in the BO because we don’t use them.
7. Same, this warning input doesn’t exist. We only use red one which is the error input. 
8. We must keep the background without any radius. And yes I agree with you, the nav pills works without background.  Here is my design proposition:
![image](https://user-images.githubusercontent.com/54888056/91046864-75042c00-e619-11ea-9376-f64eada5d689.png)


Wdyt?

**Comment by NeOMakinG** [comment]
The second proposition of toasts is undoable due to the markup which is impossible to change inside jquery growl (we can't add icons, other things are doable.

**Comment by NeOMakinG** [comment]
@prestascott what about the warning input ?

**Comment by prestascott** [comment]
@NeOMakinG What are the other things that are doable?
Isn't it the same component as the sticky alert?

About the warning input, we must keep using #759299 for the label except for the warning input which is red #F44336.

**Comment by NeOMakinG** [comment]
@prestascott it's not the same component than sticky alerts at all :/

> About the warning input, we must keep using #759299 for the label except for the warning input which is red #F44336.

Did you mean except for the error input ?

**Comment by prestascott** [comment]
Ok I see. Then we can keep the second proposition but without the icons.

**Comment by Progi1984** [comment]
Ping @NeOMakinG

**Comment by NeOMakinG** [comment]
@prestascott as you'r in rest, we try to go further as it's becoming urgent, feel free to open it again if you notice something wrong
